# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c2f1defe7b0ced31661e005bb2bd9bb0283fa87d462a49c221c6d6787acd89099caec06d2af0838a80c8b19295d5b78aa43f55672538f382d761d8e2762c819

test:
  secret_key_base: f46f7d203d81da56465d0e52a046bbc486fd913d3f5ff84e2161f6ba8a4821cf7012c55c86ce6b2c83dba9718ca1e361b9f2f1a2ea6365b4a02905b984e35486

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
